module ImGuiFSharp.Enums

type Col =
    | Text = 0
    | TextDisabled = 1
    | WindowBg = 2
    | ChildBg = 3
    | PopupBg = 4
    | Border = 5
    | BorderShadow = 6
    | FrameBg = 7
    | FrameBgHovered = 8
    | FrameBgActive = 9
    | TitleBg = 10
    | TitleBgActive = 11
    | TitleBgCollapsed = 12
    | MenuBarBg = 13
    | ScrollbarBg = 14
    | ScrollbarGrab = 15
    | ScrollbarGrabHovered = 16
    | ScrollbarGrabActive = 17
    | CheckMark = 18
    | CheckboxSelectedBg = 19
    | SliderGrab = 20
    | SliderGrabActive = 21
    | Button = 22
    | ButtonHovered = 23
    | ButtonActive = 24
    | Header = 25
    | HeaderHovered = 26
    | HeaderActive = 27
    | Separator = 28
    | SeparatorHovered = 29
    | SeparatorActive = 30
    | ResizeGrip = 31
    | ResizeGripHovered = 32
    | ResizeGripActive = 33
    | InputTextCursor = 34
    | TabHovered = 35
    | Tab = 36
    | TabSelected = 37
    | TabSelectedOverline = 38
    | TabDimmed = 39
    | TabDimmedSelected = 40
    | TabDimmedSelectedOverline = 41
    | DockingPreview = 42
    | DockingEmptyBg = 43
    | PlotLines = 44
    | PlotLinesHovered = 45
    | PlotHistogram = 46
    | PlotHistogramHovered = 47
    | TableHeaderBg = 48
    | TableBorderStrong = 49
    | TableBorderLight = 50
    | TableRowBg = 51
    | TableRowBgAlt = 52
    | TextLink = 53
    | TextSelectedBg = 54
    | TreeLines = 55
    | DragDropTarget = 56
    | DragDropTargetBg = 57
    | UnsavedMarker = 58
    | NavCursor = 59
    | NavWindowingHighlight = 60
    | NavWindowingDimBg = 61
    | ModalWindowDimBg = 62
    | Count = 63

type StyleVar =
    | Alpha = 0
    | DisabledAlpha = 1
    | WindowPadding = 2
    | WindowRounding = 3
    | WindowBorderSize = 4
    | WindowMinSize = 5
    | WindowTitleAlign = 6
    | ChildRounding = 7
    | ChildBorderSize = 8
    | PopupRounding = 9
    | PopupBorderSize = 10
    | FramePadding = 11
    | FrameRounding = 12
    | FrameBorderSize = 13
    | ItemSpacing = 14
    | ItemInnerSpacing = 15
    | IndentSpacing = 16
    | CellPadding = 17
    | ScrollbarSize = 18
    | ScrollbarRounding = 19
    | ScrollbarPadding = 20
    | GrabMinSize = 21
    | GrabRounding = 22
    | ImageRounding = 23
    | ImageBorderSize = 24
    | TabRounding = 25
    | TabBorderSize = 26
    | TabMinWidthBase = 27
    | TabMinWidthShrink = 28
    | TabBarBorderSize = 29
    | TabBarOverlineSize = 30
    | TableAngledHeadersAngle = 31
    | TableAngledHeadersTextAlign = 32
    | TreeLinesSize = 33
    | TreeLinesRounding = 34
    | DragDropTargetRounding = 35
    | ButtonTextAlign = 36
    | SelectableTextAlign = 37
    | SeparatorSize = 38
    | SeparatorTextBorderSize = 39
    | SeparatorTextAlign = 40
    | SeparatorTextPadding = 41
    | DockingSeparatorSize = 42

type MouseButton =
    | Left = 0
    | Right = 1
    | Middle = 2

type Cond =
    | None = 0
    | Always = 1
    | Once = 2
    | FirstUseEver = 4
    | Appearing = 8

type PlotScale =
    | Linear = 0
    | Time = 1
    | Log10 = 2
    | SymLog = 3

type TableBgTarget =
    | None   = 0
    | RowBg0 = 1
    | RowBg1 = 2
    | CellBg = 3

type PlotAxis =
    | X1 = 0
    | X2 = 1
    | X3 = 2
    | Y1 = 3
    | Y2 = 4
    | Y3 = 5
